---
# The authentication token for the application.
authentication: <%= if Rails.env.production? || Rails.env.staging?
  Rails.application.credentials.dig(:skylight, :authentication)
else
  ENV['SKYLIGHT_AUTHENTICATION']
end %>
